<a href="https://colab.research.google.com/github/Pramuuu/python-flask-and-first-one/blob/main/personal_numphy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [ ]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
import numpy as np
x=np.array([1,2,3,4])
print("original array:")
print(x)
print("test if none of the elements of array is zero")
print(np.all(x))
x=np.array([0,1,2,3])
print("original array:")
print(x)
print("test if none of the elements of array is zero")
print(np.all(x))

original array:
[1 2 3 4]
test if none of the elements of array is zero
True
original array:
[0 1 2 3]
test if none of the elements of array is zero
False


In [ ]:
import numpy as np
x=np.array([1,0,0,0])
print("original array:")
print(x)
print("test whether any of the elements of a given array is non zero:")
print(np.any(x))
x=np.array([0,0,0,0])
print("original array")
print(x)
print("test whether any of the elemnts of a given arrayis non zero ")
print(np.any(x))

original array:
[1 0 0 0]
test whether any of the elements of a given array is non zero:
True
original array
[0 0 0 0]
test whether any of the elemnts of a given arrayis non zero 
False


In [ ]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Test a given array element-wise for finiteness :
[ True  True False False]


In [ ]:
import numpy as np
arr=np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
arr=np.arange(10).reshape(2,-1)
print(arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
import numpy as np
mat1=np.random.random((5,3))
mat2=np.random.random((3,2))
result = np.dot(mat1,mat2)
print(result)

[[1.11070181 0.97627466]
 [0.64926203 0.53748636]
 [0.80487222 0.7907775 ]
 [0.66486112 0.52919178]
 [1.10213757 0.93025026]]


In [ ]:
import numpy as np
arr=np.arange(1,11)
odd_numbers= arr[arr%2!=0]
print(odd_numbers)

[1 3 5 7 9]
